### ISSUE TITLE
Request: add training dataset and training script to README

### ISSUE THREAD

**Issue by xuancong84** [tsurumeso/vocal-remover#101]
Thank you for open-sourcing vocal remover. I have created a usable cross-platform Karaoke system using your model (see https://github.com/xuancong84/pikaraoke). Your vocal remover works excellent on almost all human voices regardless of any language.

However, on certain synthetic singing voice, it does not work very well. (e.g., https://www.youtube.com/watch?v=8vowBJU65zg ). One of the reasons could be due to that the singing voice synthesizer does not mimic human voice very well, and your model is not trained on those kind of data.

May I know what training set do you use? (Is it from LDC or some synthetic dataset) If possible, maybe you can include your training/evaluation script (together with all hyper-parameters) as well for reproducibility of your baseline model, so that others can make further improvements on top of your model. Thanks a lot!

**Comment by tsurumeso** [comment]
Thanks for using vocal-remover for your project.
My dataset consists of 175 songs imported from my own CDs and 50 songs from DSD100. No synthetic songs are included.
The parameters used for training are described in the `Train your own model` section of the README.

**Comment by xuancong84** [comment]
Thanks for sharing your data set info! In that case, would you share your training data set in bit-torrent (or so) so that others can replicate the training process? Data on public cloud tends to survive longer because our personal storage devices will break down one day or get lost.

**Comment by tsurumeso** [comment]
My dataset cannot be shared as it would be an infringement of copyright.

**Comment by xuancong84** [comment]
In that case, is it possible for you to list the song titles of your own collection so that other people can get a closer replication of your baseline model? Thanks!
