### ISSUE TITLE
question about pre-trained data

### ISSUE THREAD

**Issue by yeonSG** [tsurumeso/vocal-remover#12]
Could you tell me about the trained data?
How much time and what data set was used?
and I want to know what options used for trained data.
thank you.

**Comment by tsurumeso** [comment]
My dataset includes 140 anime songs imported from my own CDs and 20 songs from DSD100.
The parameters for training is described in `Train your own model` section of the README.
The training took about 24 hours using 2080Ti GPU with the above settings.

**Comment by aufr33** [comment]
@tsurumeso could you clarify the following:
1) What is the maximum/minimum song length for training? Is 16 bit audio enough or 32 bit better?
2) Should I leave long intros/interludes/outros without vocals in the mix or should I cut them out?
3) Should I leave long fragments in the mix where there is no music, but only vocals? For example: https://www.youtube.com/watch?v=g19w58ot5l8
