### ISSUE TITLE
How can i fix this?? I cant run the requirements.txt file. 

### ISSUE THREAD

**Issue by D3rel** [tsurumeso/vocal-remover#14]
ERROR: Could not find a version that satisfies the requirement torch>=1.3.0 (from -r requirements.txt (line 3)) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch>=1.3.0 (from -r requirements.txt (line 3))

**Comment by tsurumeso** [comment]
I will fix this in the next version.
For now, please install PyTorch from https://pytorch.org/get-started/locally/.
And then, install the other packages.
`pip install tqdm==4.30.0 librosa==0.6.3 opencv_python==4.2.0.32`

**Comment by D3rel** [comment]
Thanks for the reply @tsurumeso, and for making the improvements! 😊
