### ISSUE TITLE
Custom sample rate

### ISSUE THREAD

**Issue by aufr33** [tsurumeso/vocal-remover#21]
Can I use custom sampling rate, for example 32000 instead of 44100? I want to do this to increase the number of pairs with the same amount of memory.

I believe that many people do not need frequencies above 16 kHz and I want to try to improve the quality in the audible range. However, I am not sure that the custom sample rate will be compatible with the default window size.

**Comment by v-nhandt21** [comment]
@aufr33  Did you have answer for this issue?
