### ISSUE TITLE
Issues Training on RTX 2080 Ti 11GB

### ISSUE THREAD

**Issue by TRvlvr** [tsurumeso/vocal-remover#22]
I've upgraded my PC recently and I now have the Nvidia Geoforce RTX 2080 Ti with 11GB's of V-RAM. I'm able to run conversions just fine with all the correct cuda drivers installed, but I'm having a lot of trouble training.  Once the data loads and it starts on the first Epoch, it just stops after a few seconds. No errors, nothing. It just closes. I tried debugging the script in Visual Studio Code to look for errors, but even then nothing, no errors. I verified my configuration and verified that my other PC with a GTX 1060 is able to run the exact same script with no issues. 

I verified there was nothing wrong with the GPU as it's able to run high end games with absolutely no issues. Have you experienced this? Is there something I need to look out for? 

System specs - 

CPU: i9 9900K
RAM: 48 GB
Motherboard: Z390 ASAP Phantom Gaming 6

**Comment by aufr33** [comment]
I have a GTX 1660ti & 32 GB RAM and had problems at first too. Reduced batch size helped me: 
python train.py -i dataset/instrumentals -m dataset/mixtures -M 0.5 --gpu 0 -b 2 -B 2

**Comment by tsurumeso** [comment]
I have not encountered that issue.
My current enviroment and settings:
```
OS: Windows10
CPU: i7-8700K
RAM: 32GB
GPU: RTX 2080 Ti
VRAM: 11GB

CUDA: 10.1
NVIDIA Driver: 431.68
Python: 3.6.8
PyTorch: 1.5.0+cu101

Batch size: 4
Training samples: 170 pairs
```

**Comment by TRvlvr** [comment]
I downloaded and installed the exact same versions as you and I got it working! Thank you so much for the assistance!

**Comment by aufr33** [comment]
Has anyone tried the Google Colab? I would like to use it instead of renting an expensive server, but I still can't figure out how to work with it.
