### ISSUE TITLE
Make voсals removal more aggressive

### ISSUE THREAD

**Issue by aufr33** [tsurumeso/vocal-remover#29]
Comparing this solution with a Spleeter, I noticed that in most cases the Spleeter keeps less vocals, but greatly degrades the quality of the accompaniment. I like the sound quality of this vocal remover better, but unfortunately it doesn’t remove all the vocals.

I would like to try to find a compromise between cleanliness and quality of accompaniment. Is it possible to adjust?

**Comment by tsurumeso** [comment]
It will be possible in the next release.
