### ISSUE TITLE
in my opinion

### ISSUE THREAD

**Issue by 404000** [tsurumeso/vocal-remover#33]
tsurumeso this vocal remover is a great project , but In my opinion, the real vocal remover must remove the singer's voice with the programmation code and the command line only, and not by train a model with a dataset(mix+instrumental) that Which i want to remove vocals from . because if I find instrumental . I will not need to train model To give me the same instrumental
plus , Imagine this instrumental is not available. What will you do , with what you will create your model?

**Comment by tsurumeso** [comment]
> In my opinion, the real vocal remover must remove the singer's voice with the programmation code and the command line only, and not by train a model with a dataset(mix+instrumental) that Which i want to remove vocals from . because if I find instrumental . I will not need to train model To give me the same instrumental

I think so, too.

> Imagine this instrumental is not available. What will you do , with what you will create your model?

This vocal-remover is not perfect. Remove vocals from every songs is impossible for now.
With that in mind, my advice is to use the same genre or the same singer's songs for training as the one you want to remove the vocals from.

**Comment by tsurumeso** [comment]
Close #48
