### ISSUE TITLE
Support 32bit float output

### ISSUE THREAD

**Issue by pburgmer** [tsurumeso/vocal-remover#34]
For further audio editing it would be best to not reduce the bit depth. Is it possible to write the output with 32bit float?

**Comment by aufr33** [comment]
`sf.write('{}_Instruments.wav'.format(basename), wav.T, sr, 'FLOAT')`

and

`sf.write('{}_Vocals.wav'.format(basename), wav.T, sr, 'FLOAT')`

**Comment by pburgmer** [comment]
Thanks. Would be great to have a command line option for that. Without editing the source code. But helps a lot to know how to do it.

**Comment by aufr33** [comment]
I also have a suggestion on command line options, so I will open a new common issue.

**Comment by Daniel-Ventura81** [comment]
how about preserving the input sample rate too? i altered the code to 96khz output and put in a hi res/96hz source file but the result was absolutely not usable. just searching a way to prevent downsampling and keep the base sample rate in output with 32bit float.

**Comment by aufr33** [comment]
@Daniel-Ventura81 

`python inference.py --input "SONG.wav" --gpu 0 -m models/baseline.pth --sr 96000`

I do not know how, but it works.

**Comment by v-nhandt21** [comment]
@aufr33 , Can I make clear, you mean that we should:

- Input 44100 -> librosa load 44100 -> model -> out 44100 -> save at 96k

or

- Input 44100 -> librosa load 96k -> model -> out 96k -> save at 96k
