### ISSUE TITLE
The end of the song remains unprocessed

### ISSUE THREAD

**Issue by aufr33** [tsurumeso/vocal-remover#35]
I found a bug in version 2.2. The last few seconds in the accompaniment are unprocessed. This is noticeable in all songs where vocals are present at the very end.

Examples:
https://www.youtube.com/watch?v=D7oSQ6wV5vU
https://www.youtube.com/watch?v=vXptzKluBLc

In version 2.1 there was no such problem.

**Comment by Dudaldy** [comment]
i have the same bug.

**Comment by Daniel-Ventura81** [comment]
jep can confirm this too

**Comment by aufr33** [comment]
A temporary solution to the problem is to pre-add 5 seconds of ultrasound using the sox:

`sox "song.wav" "bug_fix_tone_44100.wav" "fix_song.wav"`

and then remove it:

`sox "fix_song_Instruments.wav" "song_Instruments.wav" trim 0 -5`

Fix WAV - https://mega.nz/file/TVZAgK4L#-0m7vi4wn5w3xqlyRbLC-_Zn_G7wh4lnwr96DY34pGE

**Comment by aufr33** [comment]
There is no more bug in version 3.0.0
