### ISSUE TITLE
Trouble running script

### ISSUE THREAD

**Issue by peet0** [tsurumeso/vocal-remover#4]
Hi,

I really like the project, but unfortunately I'm having trouble running your script. I have Python3.7 installed, and have the required Packages installed per 'requirements.txt'. 

However, every time I try and run the script, I receive the following traceback: 

C:\vocal-remover>python inference.py --input "C:\test.wav"
loading model... done
loading wave source... done
wave source stft... Traceback (most recent call last):
  File "inference.py", line 42, in <module>
    X, phase = spec_utils.calc_spec(X, args.hop_length, phase=True)
  File "C:\vocal-remover\lib\spec_utils.py", line 22, in calc_spec
    spec_left = librosa.stft(X[0], n_fft, hop_length=hop_length)
  File "C:\Python37\lib\site-packages\librosa\core\spectrum.py", line 215, in stft
    util.valid_audio(y)
  File "C:\Python37\lib\site-packages\librosa\util\utils.py", line 278, in valid_audio
    raise ParameterError('Audio buffer is not Fortran-contiguous. '
librosa.util.exceptions.ParameterError: Audio buffer is not Fortran-contiguous. Use numpy.asfortranarray to ensure Fortran contiguity.

Any ideas? Any sort of support would be highly appreciated. I look forward to running your script in the future! :)

**Comment by AndroXD** [comment]
If my memory is correct, try downgrading librosa to version 0.6.3 or lower version, I think that's what fixed it for me.

**Comment by peet0** [comment]
Yup - you are right! That fixed it. Thanks for your help!

**Comment by padisarala** [comment]
load the wav file using the librosa package.    
 wav,sr=librosa.load(filename,sr=16000)
