### ISSUE TITLE
Quality Reduction in v3

### ISSUE THREAD

**Issue by Anjok07** [tsurumeso/vocal-remover#55]
Hello,

Quick question, I noticed there seems to be a greater reduction in the quality of the accompaniment compared to v2. Was this to make the vocal removal more aggressive? If so, what parameters need to be tweaked to bring the accompaniment quality back up to v2?

Thanks!

**Comment by 404000** [comment]
Anjok07 in version 3.0.1 tsurumuso wrote than if you want to improve the vocal removal quality with TTA, use the --tta option
Does this command line improve accompaniment quality?

**Comment by Anjok07** [comment]
> 
> 
> Anjok07 in version 3.0.1 tsurumuso wrote than if you want to improve the vocal removal quality with TTA, use the --tta option
> Does this tta improve accompaniment quality?

Not really. The quality of the accompaniment isn't even close to v2.

**Comment by 404000** [comment]
How did you know that the quality of accompaniment decreased so much?

**Comment by tsurumeso** [comment]
> Was this to make the vocal removal more aggressive? If so, what parameters need to be tweaked to bring the accompaniment quality back up to v2?

Probably so.
You can adjust the vocal removal level with the `--max_reduction_rate` option. By setting this to 0, the behavior is the same as v2.

**Comment by 404000** [comment]
Tsurumeso Integrate this command in your next update

**Comment by 404000** [comment]
Tsurumeso Will it be like this?python inference.py --input path/to/an/audio/file --max_reduction_rate 0

**Comment by tsurumeso** [comment]
It is a training option. Like this:
```
python train.py --dataset path/to/dataset --max_reduction_rate 0 --mixup_rate 0.5 --gpu 0
```

**Comment by Anjok07** [comment]
Thank you for the feedback! I will try this

**Comment by tsurumeso** [comment]
Sorry, there was a bug in v3.0.3. Please use v3.0.4 as follows:
```
python train.py --dataset path/to/dataset --reduction_rate 0 --mixup_rate 0.5 --gpu 0
```
