### ISSUE TITLE
Mixup_rate & Mixup_alpha Options 

### ISSUE THREAD

**Issue by Anjok07** [tsurumeso/vocal-remover#58]
Quick question, can you explain these options a bit more? What do the mean and how can a higher or lower mixup rate potentially affect the training process?

**Comment by aufr33** [comment]
@tsurumeso If possible, please describe briefly also the purpose of parameters:
hop_length
cropsize
patches
val_cropsize

**Comment by tsurumeso** [comment]
`mixup_rate` is a parameter that specifies the probability of applying a mixup (a data augmention technique to prevent overfitting) to each training sample.
`mixup_alpha` is a parameter that adjusts the effect of mixup.
`hop_length` is a parameter for the STFT (Short-time Fourier transform).
`patches` is a parameter that specifies the number of training samples to be cropped from a single training data.
`cropsize` is a parameter that specifies the time frame size of training samples to be cropped.
`val_cropsize` is a parameter that specifies the time frame size of validation samples to be cropped.

**Comment by Anjok07** [comment]
> 
> 
> `mixup_rate` is a parameter that specifies the probability of applying a mixup (a data augmention technique to prevent overfitting) to each training sample.
> `mixup_alpha` is a parameter that adjusts the effect of mixup.
> `hop_length` is a parameter for the STFT (Short-time Fourier transform).
> `patches` is a parameter that specifies the number of training samples to be cropped from a single training data.
> `cropsize` is a parameter that specifies the time frame size of training samples to be cropped.
> `val_cropsize` is a parameter that specifies the time frame size of validation samples to be cropped.

This really helps, thank you!
