### ISSUE TITLE
IndexError: too many indices for array

### ISSUE THREAD

**Issue by Asseel-Naji** [tsurumeso/vocal-remover#62]
Hello, Upon trying to train data with only one file in each folder (to test) I get this error :

```
line 114, in align_wave_head_and_tail
    a_mono = a[:, :sr * 4].sum(axis=0)
IndexError: too many indices for array

```
Any solution?

EDIT:
Solved : You need to make sure the dataset is stereo and has 2 tracks.

**Comment by aufr33** [comment]
One pair is not enough. You need at least 50-100.

**Comment by Asseel-Naji** [comment]
> One pair is not enough. You need at least 50-100.

I understand that, I'm asking to make sure that the error I'm getting is because there are not enough pairs or is it because of something else?

**Comment by Asseel-Naji** [comment]
Solved : You need to make sure the dataset is stereo and has 2 tracks.
