### ISSUE TITLE
Mono2stereo model?

### ISSUE THREAD

**Issue by Zcooger** [tsurumeso/vocal-remover#66]
Hello, I'm loudly thinking if it is possible with this app to make a mono to stereo model?
Do you think this application architecture allows it?
Didn't found any good way to make naturally sounding stereo audio out of single channel source yet. Even the best VST plugins do not not reach that level of quality like ML can do here.

**Comment by Asseel-Naji** [comment]
I just spent 4 hours manually copying mono into stero 2 tracks.
Please tell me there wasn't an easier way to do it.

**Comment by aufr33** [comment]
This application only splits the mix into vocals and instruments. There are other DNN that can split the mix into 4 or 5 stems from which you can create a stereo mix in a DAW.
