### ISSUE TITLE
Using fp16 instead of fp32

### ISSUE THREAD

**Issue by aufr33** [tsurumeso/vocal-remover#68]
Is it possible to train with half precision and how to do it? It turned out that versions 3.0+ is not enough 11 GB VRAM.

**Comment by tsurumeso** [comment]
It's possible, but I have no plans at the moment.
(I've been training models on a RTX2080Ti GPU with 11GB VRAM, and I haven't had any problems.)

**Comment by aufr33** [comment]
Could you please write your current settings and environment?

**Comment by Anjok07** [comment]
> It's possible, but I have no plans at the moment.
> (I've been training models on a RTX2080Ti GPU with 11GB VRAM, and I haven't had any problems.)

I'm also training on that GPU. What training perameters did you use, and how big was your dataset? (Batch size, patch size, ext.) The npy files generated are massive compared to v2.

**Comment by tsurumeso** [comment]
> What training perameters did you use

Training parameters are the same as the README.

> The npy files generated are massive compared to v2.

That's because npy files from v3 cache complex spectrograms instead of magnitude spectrograms.
However this change does not affect VRAM usage.

My current environment:
```
OS: Windows 10
CPU: i7-8700K
RAM: 32GB
GPU: RTX 2080 Ti 11GB

CUDA: 10.2
NVIDIA Driver: 460.15
Python: 3.6.8
PyTorch: 1.6.0+cu102
```
