### ISSUE TITLE
I have literally no idea why this is happening.

### ISSUE THREAD

**Issue by icandancelikecool** [tsurumeso/vocal-remover#73]
![Screenshot 2020-10-15 141833](https://user-images.githubusercontent.com/65001148/96187381-bf0adf00-0ef1-11eb-86b7-f495ed806d55.png)

**Comment by tsurumeso** [comment]
Where is the current directory?
If you don't specify a model path, `inference.py` must be run in the `vocal-remover` directory.

**Comment by icandancelikecool** [comment]
baseline.pth is in models folder.
