### ISSUE TITLE
Please Get a 'baseline.pth' model.

### ISSUE THREAD

**Issue by beIntoSW** [tsurumeso/vocal-remover#77]
I will use 'vocal-remover' in my Capstone project.
but i dont find 'baseline.pth' model.
how can i get the model??

**Comment by beIntoSW** [comment]
Oh..... Sorry... I find that~~~!!! Thank you~

**Comment by aufr33** [comment]
You can also download new models here: https://github.com/Anjok07/ultimatevocalremovergui/releases/tag/v4.0.0

**Comment by jdavidteki** [comment]
found all the assets here https://github.com/Anjok07/ultimatevocalremovergui/releases
