### ISSUE TITLE
How to run on Paperspace

### ISSUE THREAD

**Issue by atari486** [tsurumeso/vocal-remover#79]
I was trying to run the old version and ran into the "baseline.pth" issue, which I see someone has already raised. However, that person just switched to the new GUI version. This is not an option for me, as I do not have a Windows machine with a GPU powerful enough to run it. So I am stuck running the old version on a rented Paperspace machine. Is there a repository that still has baseline.pth and any other required models?

**Comment by tsurumeso** [comment]
Please download `vocal-remover-vx.x.x.zip` from [here](https://github.com/tsurumeso/vocal-remover/releases).
It contains `baseline.pth`.

**Comment by atari486** [comment]
Great, thank you very much!
